FROM python:3.10-slim

WORKDIR /app

COPY requirements-telegram.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements-telegram.txt

COPY . .

CMD ["python", "-m", "app.bot.telegram_bot"]
